<script>
let href = 'https://svelte.dev';
let name = 'world';
</script>

<style>
p { color: purple; }
a { color: blue; }
</style>

<p>Hello {name}, I'm generated by <a href={href}>svelte.dev</a>!</p>
