use Mojo::Base -strict;
use Mojo::File 'path';
use Mojolicious;
use Mojolicious::Plugin::Webpack::Builder;
use Test::Mojo;
use Test::More;

$ENV{MOJO_WEBPACK_BUILD} = 0;
my $base = path(path(__FILE__)->dirname, 'generate');
mkdir $base;
plan skip_all => "$base does not exist" unless -d $base;

my $app     = Mojolicious->new;
my $builder = Mojolicious::Plugin::Webpack::Builder->new;

note 'package.json';
is $builder->_render_to_file($app, 'package.json', $base->child('package.json'))->[0], 'generated',
  'generated package.json';
is $builder->_render_to_file($app, 'package.json', $base->child('package.json'))->[0], 'custom', 'custom package.json';

note 'webpack.config.js';
is $builder->_render_to_file($app, 'webpack.config.js', $base->child('webpack.config.js'))->[0], 'generated',
  'generated webpack.config.js';
is $builder->_render_to_file($app, 'webpack.config.js', $base->child('webpack.config.js'))->[0], 'current',
  'current webpack.config.js';

my $config = $base->child('webpack.config.js')->slurp;
$config =~ s!(Autogenerated.*)\s(\d+\.\d+)!$1 0!;
$base->child('webpack.config.js')->spurt($config);
is $builder->_render_to_file($app, 'webpack.config.js', $base->child('webpack.config.js'))->[0], 'generated',
  'regenerated webpack.config.js';

$config =~ s!(Autogenerated.*)!Custom!;
$base->child('webpack.config.js')->spurt($config);
is $builder->_render_to_file($app, 'webpack.config.js', $base->child('webpack.config.js'))->[0], 'custom',
  'custom webpack.config.js';

note 'webpack.custom.js';
my $custom = $builder->_render_to_file($app, 'webpack.custom.js', $base->child('webpack.custom.js'))->[1]->slurp;
like $custom, qr{module\.exports.*function\(config\)}, 'webpack.custom.js';

$custom = "// Do not overwrite\n\n$custom";
$base->child('webpack.custom.js')->spurt($custom);
$custom = $builder->_render_to_file($app, 'webpack.custom.js', $base->child('webpack.custom.js'))->[1]->slurp;
like $custom, qr{Do not overwrite}, 'webpack.custom.js is generated once';

done_testing;

END {
  $base->list->each(sub {unlink}) if $base;
}
