name: ci-ubuntu
on: [push, pull_request]
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - "5.30"
    container:
      image: perl:${{matrix.perl-version}}
    steps:
      - uses: actions/checkout@v2
      - name: install node 14.x on perl's container
        run: |
          apt-get update
          apt-get install -y curl
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
          cpanm -n Test::Pod Test::Pod::Coverage
      - name: Run tests
        run: prove -l t/*.t
        env:
          HARNESS_OPTIONS: j3
          TEST_ALL: 1
          TEST_POD: 1
          TEST_PUBSUB: 1
      - name: webpack version
        run: ./t/node_modules/.bin/webpack --version
